version: '3.9'
services:
  jenkins:
    image: jenkins-in-docker
    ports:
      - '49001:8080'
      - '50000:50000'
    volumes:
      - /home/vlad/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock